service: melt-api

provider:
  name: aws
  runtime: go1.x
  stage: ${opt:stage, self:custom.defaultStage}
  region: ap-northeast-1
  logRetentionInDays: 30
  timeout: 30
  versionFunctions: false
  lambdaHashingVersion: 20201221
  environment:
    NODE_ENV: ${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:*
      Resource: "arn:aws:s3:::melt-storage/*"

plugins:
  - serverless-domain-manager
  - serverless-offline

custom:
  defaultStage: dev
  environment:
    local: ${file(./config/local.yml)}
    dev: ${file(./config/development.yml)}
    prod: ${file(./config/production.yml)}
  customDomain:
    domainName: ${self:custom.environment.${self:provider.stage}.domain}
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  sites: ${file(./functions/sites/function.yml)}
  images: ${file(./functions/images/function.yml)}
