service: melt-api

provider:
  name: aws
  runtime: nodejs6.10
  stage: v1
  region: ap-northeast-1

functions:
  get_web_title:
    handler: handler.getWebTitle
    description: Webサイトのタイトルを取得する
    timeout: 30
    events:
      - http:
          path: web/title
          method: get
          cors: true
  post_note:
    handler: handler.postNote
    description: マークダウンデータをHTMLファイルで保存する
    timeout: 30
    events:
      - http:
          path: note
          method: post
          cors: true
