stage: local
domain: localhost:3000
handler:
  apps: functions/apps/main.go
  sites: functions/sites/main.go
  images: functions/images/main.go
aws:
  s3:
    bucket_name: melt-storage
  dynamodb:
    api_keys:
      table_name: melt_api_keys
