stage: prod
domain: api.melt.qazsato.com
handler:
  apps: bin/apps
  sites: bin/sites
  images: bin/images
aws:
  s3:
    bucket_name: melt-storage
  dynamodb:
    api_keys:
      table_name: melt_api_keys
